### ISSUE TITLE
Missing Tests for Source Generators

### ISSUE THREAD

**Issue by michael-hawker** [CommunityToolkit/Tooling-Windows-Submodule#30]
### Describe the bug

When I setup the `build.yml` missed copying this over from the build section:

From https://github.com/CommunityToolkit/Labs-Windows/blob/main/.github/workflows/build.yml#LL129-L131
```yaml
      - name: Run SourceGenerators tests
        id: test-generator
        run: vstest.console.exe ./tooling/CommunityToolkit.Tooling.SampleGen.Tests/bin/Release/net6.0/CommunityToolkit.Tooling.SampleGen.Tests.dll /logger:"trx;LogFileName=SourceGenerators.trx"
```

Think we can probably stick after the build step of the project-template test?

https://github.com/CommunityToolkit/Tooling-Windows-Submodule/blob/a51f9035c40a606fdadfccbee7718e0080c999db/.github/workflows/build.yml#L87-L89

### Steps to reproduce

```text
Run build, see no tests for SG
```

### Expected behavior

SG tests run as part of submodule validation here.

### Code Platform

- [ ] UWP
- [ ] WinAppSDK / WinUI 3
- [ ] Web Assembly (WASM)
- [ ] Android
- [ ] iOS
- [ ] MacOS
- [ ] Linux / GTK

### Windows Build Number

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Other (specify)

### App minimum and target SDK version

- [ ] Windows 10, version 1809 (Build 17763)
- [ ] Windows 10, version 1903 (Build 18362)
- [ ] Windows 10, version 1909 (Build 18363)
- [ ] Windows 10, version 2004 (Build 19041)
- [ ] Other (specify)
